import Head from 'next/head'
import Image from 'next/image'
import HouseList from '../components/HouseList'
import LandList from '../components/LandList'
import PropertyList from '../components/PropertyList'
import Service from '../components/Service'
import Testimonies from '../components/Testimonies'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Real Estate main page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HouseList />
        <LandList />
        <PropertyList />
        <Testimonies />
        <Service />
    </div>
  )
}
